### ISSUE TITLE
Add option to point to a specific cron file via plugin config

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/koha-plugin-crontab#11]
We currently default to the koha-shell users crontab. Some systems instead use a cron.d/koha-instance file and we should be able to use that instead... or any other location for that matter so long as the koha-instance user has read/write access appropriately

**Comment by lizrea** [comment]
fantastic idea

**Comment by mrenvoize** [comment]
On second thoughts, we decided to postpone this one.. the security implications where a little deeper on discussion (I had my suspicions, but they were confirmed after the meeting where I raised this one).

Whilst it might still be interested to do at some point, I think this is a longer term thing and also only one to even start to consider if/when Koha multi-tenancy runs under one user rather than the current user per tenant method. (I like user per tenant for security, but for performance/scale I can see the case for in app level multi-tenancy and the bugs being worked on to support that in plack/mojolicious)

**Comment by mrenvoize** [comment]
Kyle wrote the patch I was thinking of and I see no reason not to merge it. 😄
