### ISSUE TITLE
Add the ability to limit the users allowed to use the plugin

### ISSUE THREAD

**Issue by lizrea** [PTFS-Europe/koha-plugin-crontab#2]
Hi,
It would be awesome to allow only specified users to access this plugin, either through koha-conf configuration or Superlibrarian only access to the configs for this plugin.

For example, Tools->plugins permission might be too permissive, we might want to only allow support staff to access this account, or only a very few designated people at the library.

**Comment by mrenvoize** [comment]
This one is the top of my pile when I find a moment to come back to coding on this project.. if only there were more hours in the day ;P

**Comment by mrenvoize** [comment]
Thanks Kyle, the config file approach works well and is now merged.

**Comment by lizrea** [comment]
We discovered that the user allowlisting prevents new crons from being saved - Kyle is going to look into it :)
