### ISSUE TITLE
Move to admin instead of tools

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/koha-plugin-crontab#7]
I think it's a good idea for this to live under the administration pages as opposed to under tools.. as such I've submitted "[Bug 36206](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36206) - Administrative plugins" to Koha and there's a corresponding admin_plugin branch here.

**Comment by mrenvoize** [comment]
@MagnusEnger, @lizrea or @khall fancy taking a quick look at this one?

**Comment by MagnusEnger** [comment]
Sounds nice.

**Comment by lizrea** [comment]
love this!!!
